/** Side-effect imports — each file calls registerVariant() at module scope. */
import './AmberVariant'
import './ArcticVariant'
import './CatppuccinVariant'
import './CyberpunkVariant'
import './DefaultDarkVariant'
import './DraculaVariant'
import './GruvboxVariant'
import './MatrixVariant'
import './MonokaiVariant'
import './NordVariant'
import './OceanVariant'
import './SolanaVariant'
import './SolarizedVariant'
import './SunsetVariant'
import './TokyoNightVariant'
import './VaporwaveVariant'
